### ISSUE TITLE
Prompt Set with Evaluation Questions

### ISSUE THREAD

**Issue by alphacoder01** [princetonvisualai/conceptmix#1]
Hi,

Is there any plan to release the prompts and the corresponding evaluation questions used to generate the images and score them?

**Comment by XindiWu** [comment]
Hi,

Thanks for your interest! Yes, we have already released the 300 x 7 prompts used for evaluation in the [`sentence_collection`](https://github.com/princetonvisualai/conceptmix/tree/main/sentence_collection) folder for public use.

Please let us know if you have any other questions!

Thanks, 
ConceptMix Team
